name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  sftp-deploy:
    name: SFTP Deployment
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Deploy using SFTP
      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          protocol: sftp
          local-dir: ./ # Adjust this if needed
          server-dir: /public_html # Adjust this to your desired remote directory

