name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: FTP Deployment
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # Step 2: Deploy using FTP-Deploy-Action
      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./ # Adjust this to the directory you want to deploy
          server-dir: /public_html/ # Adjust this to the remote directory
